import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryClientProvider } from "$web/components/react-query-client-provider";
import { Sora as FontSans } from "next/font/google";
import { cn } from "$web/lib/utils";
import { ThemeProvider } from "$web/components/theme-provider";
import { ModeToggle } from "$web/components/mode-toggle";
import Link from "next/link";
import { Button } from "$web/components/ui/button";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ReactQueryClientProvider>
            <html lang="en">
                <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
                    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
                        {children}
                    </ThemeProvider>
                </body>
            </html>
        </ReactQueryClientProvider>
    );
}
